# Laboratorium 4 — NumPy zaawansowane
**Autor:** [Jonasz Zolisz]


In [6]:
import numpy as np


In [7]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


# ZADANIE 1

In [8]:
##zad 1a
inflacja = ceny * 1.05
print(np.round(inflacja, 2))

[[ 31.49  33.59  30.44]
 [ 52.49  55.64  50.39]
 [ 15.74  16.79  14.69]
 [104.99 110.24  99.74]]


In [9]:
##zad 1b
rabaty = np.array([0.10, 0.05, 0.15])
po_rabacie = ceny * (1 - rabaty)
print(po_rabacie)

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


In [10]:
##zad 1c
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt = ceny / (1 + marza)
print(koszt)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


# ZADANIE 2


In [12]:
##zad 2a
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


In [14]:
## zad 2b
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [18]:
##Zad 2c 
# Masz dane o sprzedaży 6 produktów jako wektor
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
# Wiesz, że to 6 produktów × 2 miesiące
# 1. Reshape na macierz 6×2
macierz = sprzedaz_flat.reshape(6, 2)
# Podpowiedź: sprzedaz_flat.reshape(6, 2) albo .reshape(-1, 2)
# 2. Oblicz średnią sprzedaż per produkt (axis=1)
srednia = macierz.mean(axis=1)
# 3. Oblicz zmianę między miesiącem 1 a 2 (kolumna 1 - kolumna 0)
# Podpowiedź: macierz[:, 1] - macierz[:, 0]
zmiana = macierz[:, 1] - macierz[:, 0]

print("Macierz:\n", macierz)
print("Średnia:", srednia)
print("Zmiana:", zmiana)

Macierz:
 [[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
Średnia: [150. 225. 215. 170. 240. 225.]
Zmiana: [100 150 -70 100 140 -70]


In [19]:
##Zad 2d
wektor = kwartaly.flatten()
nowy = np.concatenate([wektor, np.array([235])])

print(nowy)

[120 135  98 142 167 189 201 178 156 143 198 221 235]


# ZADANIE 3

In [20]:
## Dane 
np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])


In [21]:
#Zad 3a
print("Średnia:", pensje.mean())
print("Mediana:", np.median(pensje))
print("Odchylenie std:", pensje.std())

nazwy = np.array(pracownicy)

print("Powyżej średniej:", nazwy[pensje > pensje.mean()])
print("Poniżej mediany:", nazwy[pensje < np.median(pensje)])

rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)

print("Rozstęp:", rozstep)
print("IQR:", iqr)

Średnia: 6425.0
Mediana: 6050.0
Odchylenie std: 1616.9029037020127
Powyżej średniej: ['Jan' 'Marek' 'Zofia']
Poniżej mediany: ['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp: 4900
IQR: 2200.0


In [22]:
##Zad 3b
premia = np.where(oceny >= 4.5, 2000,
         np.where(oceny >= 4.0, 1000, 0))

nowe_pensje = pensje + premia

print("Premie:", premia)
print("Nowe pensje:", nowe_pensje)

print("Najwyższa premia:", pracownicy[premia.argmax()])

Premie: [1000    0 2000 1000 2000    0 1000    0]
Nowe pensje: [ 6500  7200  6800 10100  8300  4200  9500  5800]
Najwyższa premia: Ewa


In [23]:
##Zad 3c 
kolejnosc = np.argsort(pensje)[::-1]

for i, idx in enumerate(kolejnosc, 1):
    print(i, pracownicy[idx], pensje[idx], "staż:", staz[idx])

1 Marek 9100 staż: 15
2 Zofia 8500 staż: 12
3 Jan 7200 staż: 8
4 Kasia 6300 staż: 5
5 Tomek 5800 staż: 4
6 Anna 5500 staż: 3
7 Ewa 4800 staż: 2
8 Piotr 4200 staż: 1


In [24]:
## Zad 3d
korelacja_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
korelacja_staz_ocena = np.corrcoef(staz, oceny)[0, 1]

print("Staż vs pensja:", korelacja_staz_pensja)
print("Staż vs ocena:", korelacja_staz_ocena)

Staż vs pensja: 0.987862864584301
Staż vs ocena: 0.04198471605953068


In [ ]:
## Zad 3e 
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

# suma per produkt
suma_produkty = przychod.sum(axis=1)
print("Najlepszy produkt:", produkty_nazwy[suma_produkty.argmax()])

# suma per miesiąc
suma_miesiace = przychod.sum(axis=0)
print("Najlepszy miesiąc:", suma_miesiace.argmax() + 1)

# trend
pierwsze = przychod[:, :3].sum()
ostatnie = przychod[:, 3:].sum()

print("Pierwsze 3 miesiące:", pierwsze)
print("Ostatnie 3 miesiące:", ostatnie)

# ZADANIE 4

In [ ]:
##Krok 1

import numpy as np

np.random.seed(42)

wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

In [ ]:
##Krok 2
# 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)
# Podpowiedź: print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}")
print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std: {wiek.std():.1f}, min: {wiek.min()}, max: {wiek.max()}")

print(f"Wydatki — średnia: {wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, std: {wydatki.std():.1f}, min: {wydatki.min():.1f}, max: {wydatki.max():.1f}")

print(f"Wizyty — średnia: {wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, std: {wizyty.std():.1f}, min: {wizyty.min()}, max: {wizyty.max()}")

In [26]:
# 2. Korelacja wiek vs wydatki
# Podpowiedź: np.corrcoef(wiek, wydatki)[0, 1]
korelacja_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
print("Korelacja wiek vs wydatki:", korelacja_wiek_wydatki)

Korelacja wiek vs wydatki: -0.12009183441777695


In [27]:
# 3. Korelacja wizyty vs wydatki
korelacja_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]
print("Korelacja wizyty vs wydatki:", korelacja_wizyty_wydatki)

Korelacja wizyty vs wydatki: -0.15884985147948125


In [28]:
# 4. Segmentacja klientów za pomocą np.where:
# - "WYSOKI" gdy wydatki > średnia + std
# - "NISKI" gdy wydatki < średnia - std
# - "ŚREDNI" w pozostałych przypadkach
# Podpowiedź: zagnieżdżony np.where (jak w zadaniu 3b)
# sr = wydatki.mean()
# sd = wydatki.std()
# segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))
sr = wydatki.mean()
sd = wydatki.std()

segment = np.where(
    wydatki > sr + sd, "WYSOKI",
    np.where(wydatki < sr - sd, "NISKI", "ŚREDNI")
)

print(segment)

['NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'NISKI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI'
 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'NISKI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'WYSOKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'WYSOKI'
 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI']


In [29]:
# 5. Ile klientów w każdym segmencie? Użyj np.unique(..., return_counts=True)
unikalne, liczby = np.unique(segment, return_counts=True)

for s, l in zip(unikalne, liczby):
    print(s, ":", l)

NISKI : 17
WYSOKI : 12
ŚREDNI : 71
