# Laboratorium 3 — NumPy
**Autor:** Jonasz


In [1]:
import numpy as np


In [2]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")


Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [7]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")


Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [8]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


## CW 1

In [9]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru

In [11]:
print("Styczeń:", miesiace_sprzedaz[0])

Styczeń: 120


In [12]:
print("Grudzień:", miesiace_sprzedaz[-1])

Grudzień: 221


In [13]:
print("Q1:", miesiace_sprzedaz[0:3])

Q1: [120 135  98]


In [14]:
print("Q4:", miesiace_sprzedaz[-3:])

Q4: [143 198 221]


In [15]:
print("Co drugi miesiąc:", miesiace_sprzedaz[::2])

Co drugi miesiąc: [120  98 167 201 156 198]


In [16]:
print("Od tyłu:", miesiace_sprzedaz[::-1])

Od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


## CW 2

In [18]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']



In [19]:
print("Produkt A w Q2:", dane[0,1])

Produkt A w Q2: 145


In [20]:
print("Sprzedaż Produktu C:", dane[2])

Sprzedaż Produktu C: [234 267 289]


In [21]:
print("Sprzedaż wszystkich produktów w Q1:", dane[:,0])

Sprzedaż wszystkich produktów w Q1: [120  89 234  56]


In [22]:
print("Produkty B i C w Q2 i Q3:", dane[1:3, 1:3])

Produkty B i C w Q2 i Q3: [[102  95]
 [267 289]]


## Cw 3

In [23]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [24]:
print("Średnia cena:", ceny.mean())

print("Najdroższy produkt:", nazwy[ceny.argmax()], ceny.max())

print("Najtańszy produkt:", nazwy[ceny.argmin()], ceny.min())

Średnia cena: 1171.0
Najdroższy produkt: Laptop 3499
Najtańszy produkt: Ładowarka 89


In [25]:
wartosci = ceny * ilosci_magazyn

print("Wartość każdego produktu:", wartosci)

print("Łączna wartość magazynu:", wartosci.sum())

Wartość każdego produktu: [ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Łączna wartość magazynu: 549465


In [26]:
rabat = ceny * 0.85
vat = ceny * 1.23

print("Ceny po rabacie:", rabat)

print("Ceny z VAT:", vat)

print("Produkty powyżej 1000 zł:", (ceny > 1000).sum())

Ceny po rabacie: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny z VAT: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
Produkty powyżej 1000 zł: 4


In [28]:
maska = oceny_klientow >= 4.5

print("Produkty z oceną >= 4.5:", np.array(nazwy)[maska])
print("Ich ceny:", ceny[maska])

Produkty z oceną >= 4.5: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Ich ceny: [3499 2499  349 1499]


In [30]:
maska = ceny < 200

print("Produkty < 200 zł:", np.array(nazwy)[maska])
print("Ilości w magazynie:", ilosci_magazyn[maska])

Produkty < 200 zł: ['Ładowarka' 'Mysz']
Ilości w magazynie: [312 201]


In [31]:
wartosci = ceny * ilosci_magazyn

maska = ilosci_magazyn < 30

print("Produkty z niskim stanem:", np.array(nazwy)[maska])

print("Łączna wartość:", wartosci[maska].sum())

procent = wartosci[maska].sum() / wartosci.sum() * 100

print("Procent wartości magazynu:", procent)

Produkty z niskim stanem: ['Laptop' 'Monitor']
Łączna wartość: 86962
Procent wartości magazynu: 15.826667758637946


In [32]:
maska = (oceny_klientow >= 4.5) & (ceny < 1000)

print("Okazje:", np.array(nazwy)[maska])
print("Ceny:", ceny[maska])

Okazje: ['Słuchawki']
Ceny: [349]


In [33]:
print("Średnia cena (ocena >=4.0):", ceny[oceny_klientow >= 4.0].mean())

print("Średnia cena (ocena <4.0):", ceny[oceny_klientow < 4.0].mean())

Średnia cena (ocena >=4.0): 1446.142857142857
Średnia cena (ocena <4.0): 529.0


## CW 4


In [34]:
import time
# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [35]:
# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 137.8 ms
NumPy: 6.4 ms
NumPy jest 22× szybszy!


In [36]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 8.9 ms
NumPy: 1.7 ms
NumPy jest 5× szybszy!


In [37]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 65.8 ms
NumPy: 2.5 ms
NumPy jest 26× szybszy!


## Wnioski z benchmarku
- NumPy jest **...×** szybszy w mnożeniu
- NumPy jest **...×** szybszy w sumowaniu
- NumPy jest **...×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list